#pragma once

#define OK 0

#define BAD_FILE_NAME -1
#define CANT_OPEN_FILE -2
#define BAD_SCENE_PARAMS -3
#define BAD_NUMBERS_OF_ITEMS -4
#define BAD_COMMAND -5
#define BAD_NODES_PARAMS -6
#define CANT_ALLOCATE_NODES -7
#define BAD_EDGES_PARAMS -8
#define CANT_ALLOCATE_EDGES -9
#define DRAW_SCENE_ERROR -10
#define CANT_ALLOCATE_LINES -11